name: Java CI-CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NEXUS_URL: 3.83.97.95:8081
  NEXUS_REPO: maven-releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # -------------------------
    # Checkout Source Code
    # -------------------------
    - name: Checkout Repository
      uses: actions/checkout@v3

    # -------------------------
    # Setup Java & Maven
    # -------------------------
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # -------------------------
    # Build Application
    # -------------------------
    - name: Build with Maven
      run: mvn clean compile

    # -------------------------
    # SonarQube Analysis
    # -------------------------
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=java-project \
          -Dsonar.host.url=http://3.83.97.95:9000 \
          -Dsonar.login=$SONAR_TOKEN

    # -------------------------
    # Build WAR file
    # -------------------------
    - name: Build WAR file
      run: |
        mvn clean package -Drevision=0.0.1-${{ github.run_number }} -DskipTests

    # -------------------------
    # Upload to Nexus
    # -------------------------
    - name: Upload WAR to Nexus
      env:
        NEXUS_USER: ${{ secrets.NEXUSUNAME }}
        NEXUS_PASS: ${{ secrets.NEXUSPW }}
      run: |
        mvn deploy -Drevision=0.0.1-${{ github.run_number }} -DskipTests \
          -DaltDeploymentRepository=${{ env.NEXUS_REPO }}::default::http://${NEXUS_USER}:${NEXUS_PASS}@${{ env.NEXUS_URL }}/repository/${{ env.NEXUS_REPO }}

    # -------------------------
    # Build Docker Image
    # -------------------------
    - name: Build Docker Image
      run: |
        docker build -t siriya27/java-app:0.0.2-${{ github.run_number }} .

    # -------------------------
    # Login to Docker Hub
    # -------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERUNAME }}
        password: ${{ secrets.DOCKERPW }}

    # -------------------------
    # Push Docker Image
    # -------------------------
    - name: Push Docker Image
      run: |
        docker push siriya27/java-app:0.0.2-${{ github.run_number }}

